services:
  - type: web
    name: webdop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

  - type: worker
    name: webdop-backup
    env: docker
    dockerfilePath: ./Dockerfile.litestream
    envVars:
      - key: ACCESS_KEY_ID
        value: YOUR_S3_ACCESS_KEY_ID
      - key: SECRET_ACCESS_KEY
        value: YOUR_S3_SECRET_ACCESS_KEY
